#!/bin/bash
# Brain-Eleven SessionStart Hook
# Load context bootstrap from prior session + recent memories
# Called at: SessionStart event

set -e

HOOK_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
VAULT_PATH="${BRAIN_ELEVEN_VAULT:-$(cd "$HOOK_DIR/../.." && pwd)}"
SCRIPTS_DIR="$VAULT_PATH/scripts"
# Native PRE-13 hooks own context delivery after explicit installation.
[ -f "$VAULT_PATH/.brain-eleven/runtime/native-hooks-installed.json" ] && exit 0
COMPANION_DIR="$VAULT_PATH/🔮 Companion"

echo "📚 Brain-Eleven SessionStart Bootstrap"
echo "========================================"

# Step 1: Check for prior session context
echo ""
echo "1️⃣  Loading prior session context..."

if [ -f "$COMPANION_DIR/Last Session.md" ]; then
    SESSION_SIZE=$(wc -l < "$COMPANION_DIR/Last Session.md")
    if [ "$SESSION_SIZE" -gt 10 ]; then
        echo "   ✅ Found prior session ($(grep -c '^-' "$COMPANION_DIR/Last Session.md" 2>/dev/null || echo '0') decisions/lessons)"
        head -3 "$COMPANION_DIR/Last Session.md" | sed 's/^/      /'
    fi
else
    echo "   ℹ️  No prior session (first session or clean start)"
fi

# Step 2: Load validated memories (if validator has run)
echo ""
echo "2️⃣  Loading validated memories..."

if [ -f "$VAULT_PATH/.claude/validated-memory.json" ]; then
    # Simple file-size check (more reliable than JSON parsing in bash)
    MEM_SIZE=$(wc -c < "$VAULT_PATH/.claude/validated-memory.json" 2>/dev/null || echo "0")
    if [ "$MEM_SIZE" -gt 1000 ]; then
        echo "   ✅ Memory store loaded ($(du -h "$VAULT_PATH/.claude/validated-memory.json" | cut -f1))"
    fi
else
    echo "   ℹ️  No validated memories yet (Memory Validator not run)"
fi

# Step 2.5: Consume a valid compiled bootstrap when one is available. PRE-02
# made SessionEnd a fast capture hand-off, so this derived projection may have
# been generated by a legacy/manual path until the future worker owns it.
# The compiler applies the current project's retrieval scope, so this is the
# context Claude should actually receive rather than a raw store dump.
echo ""
echo "2️⃣5️⃣  Loading context bootstrap..."

CONTEXT_COMPILER="$SCRIPTS_DIR/context-compiler.py"
PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$PWD}"
if [ -f "$CONTEXT_COMPILER" ]; then
    # A persisted bootstrap is a projection, not a source of truth. The
    # compiler checks its schema, canonical revision, and project scope before
    # returning it; a different project's or stale context is never injected.
    if CONTEXT_BLOCK=$(PYTHONIOENCODING=utf-8 python3 "$CONTEXT_COMPILER" \
        --vault "$VAULT_PATH" \
        --project-root "$PROJECT_ROOT" \
        --retrieval-scope default \
        --load-bootstrap 2>/dev/null); then
        echo "   ✅ Current compiled context:"
        printf '%s\n' "$CONTEXT_BLOCK"
    else
        echo "   ℹ️  Bootstrap missing, stale, corrupt, or scope-mismatched; rebuilding safely"
        if CONTEXT_BLOCK=$(PYTHONIOENCODING=utf-8 python3 "$CONTEXT_COMPILER" \
            --vault "$VAULT_PATH" \
            --project-root "$PROJECT_ROOT" \
            --retrieval-scope default \
            --stdout 2>/dev/null); then
            printf '%s\n' "$CONTEXT_BLOCK"
        else
            echo "   ⚠️  Context could not be compiled; continuing without injected memory"
        fi
    fi
else
    echo "   ℹ️  Context compiler unavailable; skipping derived bootstrap"
fi

# Step 3: Load Open Loops
echo ""
echo "3️⃣  Loading open loops..."

if [ -f "$COMPANION_DIR/Açık Döngüler.md" ]; then
    LOOPS=$(grep -c '^\- \[' "$COMPANION_DIR/Açık Döngüler.md" 2>/dev/null || echo "0")
    echo "   📍 Open loops: $LOOPS"
    grep '^\- \[.' "$COMPANION_DIR/Açık Döngüler.md" 2>/dev/null | head -3 | sed 's/^/      /'
fi

# Step 3.5: Surface post-session maintenance findings (Phase 12)
# The report may be generated by a legacy/manual maintenance path. It can be
# missing (including while SessionEnd is capture-only) and remains
# informational only.
echo ""
echo "3️⃣5️⃣  Checking maintenance report..."

MAINTENANCE_REPORT="$VAULT_PATH/.claude/session-maintenance-report.json"
if [ -f "$MAINTENANCE_REPORT" ]; then
    PYTHONIOENCODING=utf-8 python3 - "$MAINTENANCE_REPORT" <<'PYEOF'
import json
import sys

try:
    with open(sys.argv[1], encoding="utf-8") as f:
        report = json.load(f)
except Exception:
    print("   ℹ️  Maintenance report unreadable, skipping")
    sys.exit(0)

anomalies = report.get("anomalies", {})
if not anomalies.get("ok"):
    print("   ⚠️  Last anomaly check failed - see hook-execution.log")
elif report.get("surface_at_next_session"):
    data = anomalies["data"]
    by_type = data.get("by_type", {})
    top_types = ", ".join(f"{k}: {v}" for k, v in list(by_type.items())[:3])
    print(f"   ⚠️  {data['total_anomalies']} anomalies found ({top_types})")
    print("      Run: python scripts/anomaly_detector.py --vault . for details")
else:
    print("   ✅ No anomalies detected")

digest = report.get("digest", {})
if digest.get("ok") and digest["data"].get("total_memories_considered", 0) > 0:
    print(f"   📋 {digest['data']['total_memories_considered']} memories from last session")
PYEOF
else
    echo "   ℹ️  No maintenance report yet (legacy/manual maintenance may not have run)"
fi

# Step 3.75: Check GitHub state (unmerged branches, open issues) so this
# session doesn't assume chat/NEXT.md alone is the whole picture. Added
# 2026-09-23 after an entire completed package (IG01-F) and an open
# owner-decision issue sat invisible for days on an unmerged branch — see
# CONTRIBUTING.md's "Check GitHub before assuming you know the whole
# picture." Bounded and non-fatal: any failure here (no network, gh not
# authenticated, git/gh missing) is reported and skipped, never blocks the
# rest of this hook.
echo ""
echo "3️⃣75️⃣  Checking GitHub state..."

if command -v gh >/dev/null 2>&1 && command -v git >/dev/null 2>&1; then
    if timeout 8 git -C "$VAULT_PATH" fetch origin --quiet 2>/dev/null; then
        UNMERGED=$(git -C "$VAULT_PATH" for-each-ref --format='%(refname:short)' refs/remotes/origin --no-merged=origin/master 2>/dev/null | grep -v '^origin/HEAD$' || true)
        UNMERGED_COUNT=$(printf '%s' "$UNMERGED" | grep -c . || true)
        if [ "$UNMERGED_COUNT" -gt 0 ]; then
            echo "   ⚠️  $UNMERGED_COUNT remote branch(es) not merged into origin/master:"
            printf '%s\n' "$UNMERGED" | sed 's/^/      /' | head -10
        else
            echo "   ✅ No unmerged remote branches"
        fi
    else
        echo "   ℹ️  git fetch failed or timed out; skipping branch check (not fatal)"
    fi

    if OPEN_ISSUES=$(timeout 8 gh issue list --state open --limit 20 --json number,title 2>/dev/null); then
        ISSUE_LINES=$(printf '%s' "$OPEN_ISSUES" | python3 -c "
import json, sys
try:
    issues = json.load(sys.stdin)
except Exception:
    issues = []
for i in issues:
    print(f\"#{i['number']}: {i['title']}\")
" 2>/dev/null)
        if [ -n "$ISSUE_LINES" ]; then
            ISSUE_COUNT=$(printf '%s\n' "$ISSUE_LINES" | grep -c .)
            echo "   ⚠️  $ISSUE_COUNT open GitHub issue(s):"
            printf '%s\n' "$ISSUE_LINES" | sed 's/^/      /'
        else
            echo "   ✅ No open GitHub issues"
        fi
    else
        echo "   ℹ️  gh issue list failed or timed out; skipping (not fatal, may need 'gh auth login')"
    fi
else
    echo "   ℹ️  git or gh CLI unavailable; skipping GitHub state check"
fi

# Step 4: Display ready status
echo ""
echo "========================================"
echo "✅ SessionStart bootstrap complete"
echo ""
echo "Available:"
echo "  📖 Last Session (.../Last Session.md)"
echo "  🎯 Open Loops (.../Açık Döngüler.md)"
echo "  💾 Memory Store (.claude/validated-memory.json)"
echo ""
echo "Next:"
echo "  - Review prior decisions and lessons"
echo "  - Check for superseded or resolved memories"
echo "  - Update Daily.md at session end"
echo ""
