"""Canonical memory package surface for the strangler migration."""

from .store import (
    CANONICAL_SCHEMA_VERSION,
    MemoryStore,
    MemoryStoreConflict,
    MemoryStoreCorrupt,
    MemoryStoreError,
    no_change,
)
from .scope import (
    ALL_RETRIEVAL_SCOPE,
    DEFAULT_RETRIEVAL_SCOPE,
    GLOBAL_RETRIEVAL_SCOPE,
    GLOBAL_SCOPE,
    PROJECT_RETRIEVAL_SCOPE,
    PROJECT_SCOPE,
    VALID_RETRIEVAL_SCOPES,
    VALID_SCOPES,
    filter_memories,
    fingerprint_aliases,
    infer_memory_scope,
    legacy_content_fingerprint,
    legacy_project_id,
    normalize_content,
    normalize_project_root,
    project_identity,
    registered_project_identity,
    resolve_capture_scope,
    resolve_retrieval_project,
    resolved_project_identity,
    scope_sort_key,
    scoped_fingerprint,
)

__all__ = [
    "CANONICAL_SCHEMA_VERSION",
    "MemoryStore",
    "MemoryStoreConflict",
    "MemoryStoreCorrupt",
    "MemoryStoreError",
    "no_change",
    "ALL_RETRIEVAL_SCOPE",
    "DEFAULT_RETRIEVAL_SCOPE",
    "GLOBAL_RETRIEVAL_SCOPE",
    "GLOBAL_SCOPE",
    "PROJECT_RETRIEVAL_SCOPE",
    "PROJECT_SCOPE",
    "VALID_RETRIEVAL_SCOPES",
    "VALID_SCOPES",
    "filter_memories",
    "fingerprint_aliases",
    "infer_memory_scope",
    "legacy_content_fingerprint",
    "legacy_project_id",
    "normalize_content",
    "normalize_project_root",
    "project_identity",
    "registered_project_identity",
    "resolve_capture_scope",
    "resolve_retrieval_project",
    "resolved_project_identity",
    "scope_sort_key",
    "scoped_fingerprint",
]
